name: note prompt cli test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: setting up python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: run cli
      run: |
        python cli.py --help